name: 'run-benchmarks'
description: 'Run Artipie Benchmarks Github action'
branding:
  icon: trending-up
  color: green
inputs:
  aws-access-key:
    description: 'AWS access key to create perfomance tests environment'
    required: true
  aws-secret-key:
    description: 'AWS secret key to create perfomance tests environment'
    required: true
  version:
    description: 'Docker tag of Artipie image to test'
    required: true
outputs:
  report:
    description: 'Report containing JSON file with benchmarking results'
runs:
  using: 'docker'
  image: Dockerfile
  env:
    ARTIPIE_VERSION: ${{ inputs.version }}
    TF_VAR_access_key: ${{ inputs.aws-access-key }}
    TF_VAR_secret_key: ${{ inputs.aws-secret-key }}
